apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: bookstore-split
  namespace: bookstore
spec:
  service: bookstore.bookstore # <root-service>.<namespace>
  backends:
  - service: bookstore-v1 # matches app:bookstore,version:v1
    weight: 0
  - service: bookstore-v2 # matches app:bookstore,version:v2
    weight: 100
